export const ACTION_TYPE = {
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    SET_POST_DATA: "SET_POST_DATA",
    SET_POST_COMMENT: "SET_POST_COMMENT",
    CLOSE_MODAL: "CLOSE_MODAL",
    OPEN_MODAL: "OPEN_MODAL",
    RESET_POST_DATA: "RESET_POST_DATA",
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT",
};
